### ISSUE TITLE
Error on installing signed apk

### ISSUE THREAD

**Issue by dhzdhd** [dhzdhd/OpenSMS#1]
APK signed and verified with jarsigner errors out during install with the error -

`adb: failed to install .\app-universal-release-unsigned.apk: Failure [INSTALL_FAILED_INVALID_APK: INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]`

Possible explanation for this is a [related issue](https://github.com/iBotPeaches/Apktool/issues/1626)

**Comment by oneeb-asad** [comment]
> APK signed and verified with jarsigner errors out during install with the error -
> 
> `adb: failed to install .\app-universal-release-unsigned.apk: Failure [INSTALL_FAILED_INVALID_APK: INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]`
> 
> Possible explanation for this is a [related issue](https://github.com/iBotPeaches/Apktool/issues/1626)

currently facing this issue and have you resolved this issue?

**Comment by dhzdhd** [comment]
> currently facing this issue and have you resolved this issue?

I have not resolved this issue directly, no. However, the app is not manually signed anymore and uses a GitHub action to do all the building, packaging and signing which works just fine.
